### ISSUE TITLE
postgresql docker

### ISSUE THREAD

**Issue by smshack** [smshack/express-template#7]

**Comment by smshack** [comment]
```
version: '3.1'
services:
    postgres:
        image: postgres
        ports:
            - '5432:5432'
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: test_db
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
```
![image](https://github.com/smshack/express-template/assets/46982752/e54a8c43-a2a0-4ac4-94bb-b487693f5a23)
